title: LED-flower
hero_image: images/banner.png
description: LED-flower description
version: 4
listed: false
copyedit: false
last_tested: "2020-02-11"
steps:
  - title: Introduction
  - title: "Set up your LEDs"
  - title: "Make your flower"
  - title: "Add to the bouquet"
